/** @type {import('tailwindcss').Config} */
module.exports = {
  // dev 서버가 이 폴더가 아닌 상위 폴더에서 실행될 수도 있어서(cwd 불일치),
  // content 경로는 이 설정 파일 위치 기준 절대경로로 지정함 (path 모듈 대신
  // 문자열 결합 - vite.config.js가 ESM으로 번들링될 때 require("path")가
  // 깨지는 문제가 있었음).
  content: [
    `${__dirname}/index.html`,
    `${__dirname}/src/**/*.{js,jsx}`,
  ],
  theme: {
    extend: {
      colors: {
        outline: "#757687",
        "primary-fixed-dim": "#bcc2ff",
        "on-surface": "#191c1e",
        "primary-fixed": "#dfe0ff",
        "on-surface-variant": "#444655",
        "secondary-fixed-dim": "#b7c8e1",
        "on-tertiary": "#ffffff",
        "inverse-surface": "#2d3133",
        surface: "#f7f9fb",
        "on-primary-container": "#dfe0ff",
        "tertiary-container": "#af4100",
        background: "#f7f9fb",
        "on-tertiary-container": "#ffdbce",
        "on-tertiary-fixed-variant": "#7e2c00",
        "on-primary": "#ffffff",
        "on-tertiary-fixed": "#360f00",
        "surface-container-low": "#f2f4f6",
        "surface-container-lowest": "#ffffff",
        "on-secondary": "#ffffff",
        "on-error": "#ffffff",
        "on-error-container": "#93000a",
        "on-background": "#191c1e",
        "inverse-on-surface": "#eff1f3",
        "on-secondary-fixed": "#0b1c30",
        "surface-bright": "#f7f9fb",
        "surface-variant": "#e0e3e5",
        "surface-tint": "#364be1",
        primary: "#1e35d0",
        "surface-container-high": "#e6e8ea",
        "outline-variant": "#c5c5d8",
        "on-primary-fixed": "#000b62",
        tertiary: "#883100",
        "on-primary-fixed-variant": "#132cca",
        "surface-dim": "#d8dadc",
        "secondary-container": "#d0e1fb",
        "secondary-fixed": "#d3e4fe",
        "on-secondary-container": "#54647a",
        "primary-container": "#3e52e8",
        "tertiary-fixed-dim": "#ffb597",
        "inverse-primary": "#bcc2ff",
        "surface-container-highest": "#e0e3e5",
        error: "#ba1a1a",
        "surface-container": "#eceef0",
        secondary: "#505f76",
        "on-secondary-fixed-variant": "#38485d",
        "tertiary-fixed": "#ffdbcd",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        xl: "32px",
        xs: "8px",
        "max-content-width": "1200px",
        lg: "24px",
        sm: "12px",
        base: "4px",
        md: "16px",
        "sidebar-width": "280px",
      },
      fontFamily: {
        "body-lg": ["Inter"],
        "body-md-bold": ["Inter"],
        "label-sm": ["Inter"],
        "body-md": ["Inter"],
        "headline-lg": ["Manrope"],
        "headline-md": ["Manrope"],
      },
      fontSize: {
        "body-lg": ["16px", { lineHeight: "24px", letterSpacing: "0", fontWeight: "400" }],
        "body-md-bold": ["14px", { lineHeight: "20px", letterSpacing: "0", fontWeight: "600" }],
        "label-sm": ["12px", { lineHeight: "16px", letterSpacing: "0.02em", fontWeight: "500" }],
        "body-md": ["14px", { lineHeight: "20px", letterSpacing: "0", fontWeight: "400" }],
        "headline-lg": ["30px", { lineHeight: "38px", letterSpacing: "-0.02em", fontWeight: "700" }],
        "headline-md": ["24px", { lineHeight: "32px", letterSpacing: "-0.01em", fontWeight: "600" }],
      },
    },
  },
  plugins: [],
};
