name: Test minimal

on:
  workflow_dispatch:

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Decode ID
        run: echo "ID=$(echo '${{ secrets.YONSEI_ID_B64 }}' | base64 -d)" >> "$GITHUB_ENV"
      - run: echo "ID is $ID"
